import { Inter, Poppins } from "next/font/google";
import "@/app/globals.css";
import { Navbar } from "@/components/navbar";
import { Toaster } from 'react-hot-toast'
import Head from "next/head";

import { Sidebar } from "@/components/Sidebar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}


const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning >
            <Head>
                <link
                    rel="stylesheet"
                    href="https://unpkg.com/react-quill@1.3.3/dist/quill.snow.css"
                />
            </Head>
            <body className={inter.className}>

                <Navbar />
                <Toaster />
                <div className="flex h-screen w-full" >
                    <Sidebar />
                    <div className="w-full px-4 pt-5">
                        {children}
                    </div>

                </div>
            </body>
        </html>
    )
}